# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74bf1f3ccdc04e36dd277c435ac9dceb1d5c2a1550dfed787e015b56eb99f6678d68fdf081d13430cf474f6ebcc9bd58592e6c05768cd7c22987e8a875c1fd32

test:
  secret_key_base: 16f99a560dd4388afc7488485b1dd0af0ee1ffbeed18a0f3f61bd23f9d04ef9c152d8760628f85e5c834caeccd50c93bbef7d7b992c3fe6eaae4539ddb9808b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
